"""empty message

Revision ID: 23e8b89664d4
Revises: 392e77fb0db9
Create Date: 2020-02-08 08:30:45.960962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23e8b89664d4"
down_revision = "392e77fb0db9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("plays", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "plays")
    # ### end Alembic commands ###
