"""empty message

Revision ID: 392e77fb0db9
Revises: 778b7ac125ed
Create Date: 2020-02-08 06:05:25.868500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "392e77fb0db9"
down_revision = "778b7ac125ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "admin")
    # ### end Alembic commands ###
