"""empty message

Revision ID: 542c47842d61
Revises: 795783c44933
Create Date: 2020-02-11 01:50:15.816888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "542c47842d61"
down_revision = "795783c44933"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("profile_picture_url", sa.String(length=140), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "profile_picture_url")
    # ### end Alembic commands ###
