"""empty message

Revision ID: 778b7ac125ed
Revises: d61b2dccfbfd
Create Date: 2020-02-06 23:06:30.515390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "778b7ac125ed"
down_revision = "d61b2dccfbfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("poster", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "poster")
    # ### end Alembic commands ###
