"""empty message

Revision ID: 795783c44933
Revises: 23e8b89664d4
Create Date: 2020-02-08 22:12:36.482548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "795783c44933"
down_revision = "23e8b89664d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("receives_mail", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "receives_mail")
    # ### end Alembic commands ###
