"""empty message

Revision ID: 97d71cd2fca1
Revises: 48612c2b4c70
Create Date: 2020-02-03 01:15:21.435543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "97d71cd2fca1"
down_revision = "48612c2b4c70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("url", sa.String(length=140), nullable=True))
    op.drop_column("post", "body")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("body", mysql.VARCHAR(length=140), nullable=True))
    op.drop_column("post", "url")
    # ### end Alembic commands ###
