"""empty message

Revision ID: c85b7622c4e5
Revises: 542c47842d61
Create Date: 2020-02-11 15:18:38.591124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c85b7622c4e5"
down_revision = "542c47842d61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("github", sa.String(length=140), nullable=True))
    op.add_column("user", sa.Column("instagram", sa.String(length=140), nullable=True))
    op.add_column("user", sa.Column("twitter", sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "twitter")
    op.drop_column("user", "instagram")
    op.drop_column("user", "github")
    # ### end Alembic commands ###
