"""empty message

Revision ID: d61b2dccfbfd
Revises: 97d71cd2fca1
Create Date: 2020-02-06 19:47:15.903888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d61b2dccfbfd"
down_revision = "97d71cd2fca1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("body", sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "body")
    # ### end Alembic commands ###
